version: '3'
services:
  nginx:
    image: nginx:1.15
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./http.conf:/etc/nginx/conf.d/default.conf
      - ./https.conf:/etc/nginx/conf.d/https.conf
      - ./example.key:/etc/nginx/ssl/example.key
      - ./example.crt:/etc/nginx/ssl/example.crt
  serving:
    image: node:11.12
    hostname: serving
    ports:
      - "3000:3000"
    volumes:
      - ./serving.js:/bin/serving.js
    command: bash -c "node /bin/serving.js"
  searching:
    image: node:11.12
    hostname: searching
    ports:
      - "3001:3001"
    volumes:
      - ./searching.js:/bin/searching.js
    command: bash -c "node /bin/searching.js"
